# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Catalog\Infrastructure\Api\ShopifyClient:
        arguments:
            $httpClient: '@http_client'
            $apiVersion: '%env(SHOPIFY_API_VERSION)%'
        tags:
            - { name: symfony.client }

    App\Catalog\Application\Command\DispatchTenantsCollectionsSync\DispatchTenantsCollectionsSyncHandler:
        arguments:
            $batchSize: 100

    App\Catalog\Application\Command\AcquireTenantsCollectionsForSync\AcquireTenantsCollectionsForSyncHandler:
        arguments:
            $batchSize: 100

    App\Catalog\Application\Command\ProcessTenantCollectionSync\ProcessTenantCollectionSyncHandler:
        arguments:
            $productPageSize: 250

    App\Catalog\Application\Command\RescheduleStuckTenantsCollectionsSync\RescheduleStuckTenantsCollectionsSyncHandler:
        arguments:
            $stuckThresholdMinutes: 5
