# yaml-language-server: $schema=../../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

services:
    _defaults:
        autowire: true
        autoconfigure: true

    App\Tenancy\Infrastructure\Shopify\ShopifyOAuthClient:
        arguments:
            $httpClient: '@http_client'
            $apiKey: '%env(SHOPIFY_API_KEY)%'
            $apiSecret: '%env(SHOPIFY_API_SECRET)%'
        tags:
            - { name: symfony.client }

    App\Tenancy\Domain\Service\OAuth\ShopifyOAuthClientInterface: '@App\Tenancy\Infrastructure\Shopify\ShopifyOAuthClient'
