doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        server_version: '18'
        profiling_collect_backtrace: '%kernel.debug%'
        types:
            encrypted_string: App\Shared\Infrastructure\Doctrine\Type\EncryptedStringType
            jsonb: App\Shared\Infrastructure\Doctrine\Type\JsonbType
            tenant_status: App\Tenancy\Infrastructure\Doctrine\Type\TenantStatusType
        mapping_types:
            jsonb: jsonb
            tenant_status: tenant_status
    orm:
        validate_xml_mapping: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        identity_generation_preferences:
            Doctrine\DBAL\Platforms\PostgreSQLPlatform: identity
        auto_mapping: true
        mappings:
            Tenancy:
                type: attribute
                is_bundle: false
                dir: '%kernel.project_dir%/src/Tenancy/Domain/Model'
                prefix: 'App\Tenancy\Domain\Model'
                alias: Tenancy

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
