# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

imports:
    - { resource: 'services/defaults.yaml' }
    - { resource: 'services/shared.yaml' }
    - { resource: 'services/identity.yaml' }
    - { resource: 'services/tenancy.yaml' }
    - { resource: 'services/catalog.yaml' }
    - { resource: 'services/audit.yaml' }
